import type { AssetCatalog, AssetEntry } from './AssetManager';

const ASSET_ROOT = '/assets/energy_grid_asset_pack';

const GRID_DEFENSE_ASSETS = [
  ['griddef_buildings_power_plant', 'buildings/power_plant.png', 180, 134, 'buildings'],
  ['griddef_buildings_substation_hub', 'buildings/substation_hub.png', 197, 134, 'buildings'],
  ['griddef_effects_arc_propagation', 'effects/arc_propagation.png', 144, 95, 'effects'],
  ['griddef_effects_battery_discharge_effect', 'effects/battery_discharge_effect.png', 116, 109, 'effects'],
  ['griddef_effects_blackout_wave', 'effects/blackout_wave.png', 143, 110, 'effects'],
  ['griddef_effects_chain_lightning', 'effects/chain_lightning.png', 147, 101, 'effects'],
  ['griddef_effects_impact_electric', 'effects/impact_electric.png', 133, 95, 'effects'],
  ['griddef_effects_line_damage', 'effects/line_damage.png', 138, 110, 'effects'],
  ['griddef_effects_line_overheat', 'effects/line_overheat.png', 141, 110, 'effects'],
  ['griddef_effects_monster_death_effect', 'effects/monster_death_effect.png', 137, 99, 'effects'],
  ['griddef_effects_overload_charge', 'effects/overload_charge.png', 127, 82, 'effects'],
  ['griddef_effects_recovery_wave', 'effects/recovery_wave.png', 143, 110, 'effects'],
  ['griddef_effects_spark_explosion', 'effects/spark_explosion.png', 127, 113, 'effects'],
  ['griddef_grid_nodes_line_damaged_overheat', 'grid_nodes/line_damaged_overheat.png', 236, 128, 'grid_nodes'],
  ['griddef_grid_nodes_line_off', 'grid_nodes/line_off.png', 218, 128, 'grid_nodes'],
  ['griddef_grid_nodes_normal_node', 'grid_nodes/normal_node.png', 151, 118, 'grid_nodes'],
  ['griddef_grid_nodes_switch_node_closed', 'grid_nodes/switch_node_closed.png', 154, 118, 'grid_nodes'],
  ['griddef_grid_nodes_switch_node_open', 'grid_nodes/switch_node_open.png', 153, 118, 'grid_nodes'],
  ['griddef_monsters_armored_break_armor', 'monsters_armored/break_armor.png', 85, 111, 'monsters_armored'],
  ['griddef_monsters_armored_death', 'monsters_armored/death.png', 110, 95, 'monsters_armored'],
  ['griddef_monsters_armored_hit', 'monsters_armored/hit.png', 81, 111, 'monsters_armored'],
  ['griddef_monsters_armored_walk', 'monsters_armored/walk.png', 81, 111, 'monsters_armored'],
  ['griddef_monsters_boss_death', 'monsters_boss/death.png', 166, 102, 'monsters_boss'],
  ['griddef_monsters_boss_hit', 'monsters_boss/hit.png', 92, 126, 'monsters_boss'],
  ['griddef_monsters_boss_roar', 'monsters_boss/roar.png', 96, 131, 'monsters_boss'],
  ['griddef_monsters_boss_walk', 'monsters_boss/walk.png', 90, 126, 'monsters_boss'],
  ['griddef_monsters_small_death', 'monsters_small/death.png', 81, 90, 'monsters_small'],
  ['griddef_monsters_small_electro_stun', 'monsters_small/electro_stun.png', 125, 104, 'monsters_small'],
  ['griddef_monsters_small_hit', 'monsters_small/hit.png', 75, 90, 'monsters_small'],
  ['griddef_monsters_small_walk', 'monsters_small/walk.png', 75, 90, 'monsters_small'],
  ['griddef_rifts_east_rift_left', 'rifts/east_rift_left.png', 176, 250, 'rifts'],
  ['griddef_rifts_north_rift_down', 'rifts/north_rift_down.png', 198, 250, 'rifts'],
  ['griddef_states_battery_charging', 'states/battery_charging.png', 167, 116, 'states'],
  ['griddef_states_battery_discharging', 'states/battery_discharging.png', 219, 116, 'states'],
  ['griddef_states_hospital_blackout', 'states/hospital_blackout.png', 180, 125, 'states'],
  ['griddef_states_hospital_powered', 'states/hospital_powered.png', 172, 125, 'states'],
  ['griddef_states_industrial_blackout', 'states/industrial_blackout.png', 192, 99, 'states'],
  ['griddef_states_industrial_powered', 'states/industrial_powered.png', 188, 99, 'states'],
  ['griddef_states_mall_blackout', 'states/mall_blackout.png', 161, 125, 'states'],
  ['griddef_states_mall_powered', 'states/mall_powered.png', 180, 125, 'states'],
  ['griddef_states_residential_blackout', 'states/residential_blackout.png', 174, 125, 'states'],
  ['griddef_states_residential_powered', 'states/residential_powered.png', 182, 125, 'states'],
  ['griddef_ui_battery_energy_bar', 'ui/battery_energy_bar.png', 152, 46, 'ui'],
  ['griddef_ui_boss_incoming', 'ui/boss_incoming.png', 81, 54, 'ui'],
  ['griddef_ui_close_zone', 'ui/close_zone.png', 73, 61, 'ui'],
  ['griddef_ui_countdown_timer', 'ui/countdown_timer.png', 106, 49, 'ui'],
  ['griddef_ui_defeat_panel', 'ui/defeat_panel.png', 118, 69, 'ui'],
  ['griddef_ui_force_overload', 'ui/force_overload.png', 71, 61, 'ui'],
  ['griddef_ui_hospital_alarm', 'ui/hospital_alarm.png', 73, 54, 'ui'],
  ['griddef_ui_next_wave', 'ui/next_wave.png', 74, 61, 'ui'],
  ['griddef_ui_one_star', 'ui/one_star.png', 64, 60, 'ui'],
  ['griddef_ui_pause', 'ui/pause.png', 72, 61, 'ui'],
  ['griddef_ui_restart', 'ui/restart.png', 73, 61, 'ui'],
  ['griddef_ui_switch_route', 'ui/switch_route.png', 76, 61, 'ui'],
  ['griddef_ui_three_star', 'ui/three_star.png', 134, 60, 'ui'],
  ['griddef_ui_two_star', 'ui/two_star.png', 100, 60, 'ui'],
  ['griddef_ui_victory_panel', 'ui/victory_panel.png', 119, 69, 'ui'],
  ['griddef_ui_wave_start', 'ui/wave_start.png', 70, 54, 'ui'],
] as const;

export const city01GridDefenseAssetCatalog: AssetCatalog = {
  schemaVersion: 1,
  budgetBytes: 5_000_000,
  entries: GRID_DEFENSE_ASSETS.map(([id, relativePath, width, height, group]): AssetEntry => ({
    id,
    kind: 'image',
    src: `${ASSET_ROOT}/${relativePath}`,
    version: 1,
    preload: 'lazy',
    width,
    height,
    tags: ['city01', 'battle', 'grid-defense', group]
  }))
};
